# Generated by Django 3.0.5 on 2021-06-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20210616_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('9:00 - 10:00', '9:00 - 10:00'), ('10:00 - 11:00', '11:00 - 12:00'), ('12:00 - 1:00', '12:00 - 1:00'), ('2:00 - 3:00', '2:00 - 3:00'), ('3:00 - 4:00', '3:00 - 4:00'), ('4:00 - 5:00', '4:00 - 5:00')], default='9:00 - 10:00', max_length=50),
        ),
    ]
